INSERT INTO roles (name, created_at, updated_at) VALUES
    ('ADMIN', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('MANAGER', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6)),
    ('EMPLOYEE', CURRENT_TIMESTAMP(6), CURRENT_TIMESTAMP(6));
